services:
  api:
    image: ruby
    container_name: api
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./api:/app
      - rubygems:/usr/local/bundle
    working_dir: /app
    command: bash -c "bundle install && rackup"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

  sidekiq:
    image: ruby
    container_name: sidekiq
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./api:/app
      - rubygems:/usr/local/bundle
    working_dir: /app
    command: bash -c "bundle install && sidekiq -r ./lib/import_job.rb"
    depends_on:
      - redis
      - postgres
      - api

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./api/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  rubygems:
