services:
  api:
    image: ruby
    container_name: api
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    working_dir: /app
    command: bash -c "bundle install && rackup"
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  rubygems:
