services:
  server:
    image: ruby
    container_name: server
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    working_dir: /app
    command: bash -c "bundle install && rackup -p 3000 -o 0.0.0.0"
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    container_name: postres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  rubygems:
